### ISSUE TITLE
Filepath can contains space. 

### ISSUE THREAD

**Issue by th0was14** [nithinpeter/jest-run-it#1]
Can you add quote ? 

https://github.com/nithinpeter/jest-run-it/blob/2e4aaa82007407bf820e69b58c519db760d857b0/src/commands.ts#L10

**Comment by nithinpeter** [comment]
Hey thanks for reporting the issue. Can you raise a pull request to fix it? 🙂

**Comment by th0was14** [comment]
yes, i can do that

**Comment by nithinpeter** [comment]
Thanks, will soon release a version with the fix.
