### ISSUE TITLE
Buttons disapear with nested describes

### ISSUE THREAD

**Issue by pierralex** [nithinpeter/jest-run-it#20]
Hello, 
This works fine
```
  describe('Method1', () => {
    test('xxxx', () => {
     ....
    });
  });
  describe('Method2', () => {
    test('yyyy', () => {
      .....
    });

    test('zzzzzz', () => {
      ...
    });
  });
```

But if I add a surronding describe for the class name, the buttons to launch the tests disapear (above each describe and each test)
```
describe('ClassName', () => {
  describe('Method1', () => {
    test('xxxx', () => {
     ....
    });
  });
  describe('Method2', () => {
    test('yyyy', () => {
      .....
    });

    test('zzzzzz', () => {
      ...
    });
  });
});
```

**Comment by nithinpeter** [comment]
Thank you for raising the issue. But nested "describes" seems to work for me. 

Here is a screenshot:
![Screen Shot 2020-11-23 at 8 56 21 pm](https://user-images.githubusercontent.com/10738296/99949063-88689400-2dce-11eb-9a3e-a2f6e22c2bd3.png)

Can you please check again?

**Comment by pierralex** [comment]
Hello,
It is now working on my side as well (sorry I forgot I opened the issue). I don't know if I changed my setup or just a VS update fixed it. But I am closing the issue.

**Comment by nithinpeter** [comment]
I am going to close this, please feel free to reopen if you still have the problem.
