### ISSUE TITLE
[feature/bug] can we allow this shortcut to work not just .spec.xx files but also .integration-spec.xx files?

### ISSUE THREAD

**Issue by achenwei-chwy** [nithinpeter/jest-run-it#23]
When a file is ending with .integration-spec.xx (xx can be ts or js), the shortcut no longer work.
Maybe there is a config I can tweak to allow more than just .spec.xx files so the Run | Debug shortcut can work properly in VS Code?

Also is this the same plugin that already been integrated into VS Code?

**Comment by nithinpeter** [comment]
There is a config option to specify the test file pattern. See the full list of config options here: https://github.com/nithinpeter/jest-run-it#config-options
