### ISSUE TITLE
can't run when test name has quotes in it

### ISSUE THREAD

**Issue by safareli** [nithinpeter/jest-run-it#28]
I had test a test like `it("Can't decode", () => {` and when I try to run I see this in terminal

```sh
$ node_modules/.bin/jest '/Users/safareli/dev/project/test/codec\.spec\.ts' -t 'Can\'t decode'
quote>
```

**Comment by nithinpeter** [comment]
There is a config option to set the quote kind (double/single) to use. You can set it to "double" and that might fix this issue.
![Uploading Screen Shot 2020-12-21 at 2.35.00 pm.png…]()

**Comment by safareli** [comment]
thanks
